### ISSUE TITLE
Error during parsing declarations of new PHP functions "exit" and "die" in phpstorm-stubs

### ISSUE THREAD

**Issue by isfedorov** [nikic/PHP-Parser#1030]
Hi Nikita, I'm trying to adapt tests in [phpstorm-stubs](https://github.com/JetBrains/phpstorm-stubs) repo for new PHP 8.4 and face a problem that parser fails to parse declarations for new PHP functions `exit` and `die`. The case is next: stubs contain a file with functions declarations
```
function exit(string|int $status = 0): never {}

function die(string|int $status = 0): never {}
```
But when I try to parse them, parser throws exception `Syntax error, unexpected T_EXIT, expecting T_STRING or T_READONLY or '('`
Parser is configured to use the latest available version `$parser = new ParserFactory()->createForNewestSupportedVersion();` but still it doesn't work. The simplified code of parser is next
```
<?php
include __DIR__ . '/vendor/autoload.php';

use PhpParser\Node\Stmt\Function_;
use PhpParser\NodeTraverser;
use PhpParser\ParserFactory;

class ASTVisitor extends \PhpParser\NodeVisitorAbstract
{
    public function enterNode(\PhpParser\Node $node)
    {
        if ($node instanceof Function_) {
            $name = $node->name;
        }
    }
}

class Parser {
    public static function parse()
    {
        $parser = new ParserFactory()->createForNewestSupportedVersion();

        $stubsIterator =
            new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator(__DIR__ . '/src', FilesystemIterator::SKIP_DOTS)
            );
        $visitor = new ASTVisitor();
        $traverser = new NodeTraverser();
        $traverser->addVisitor($visitor);

        foreach ($stubsIterator as $file) {
            $code = file_get_contents($file->getRealPath());
            $traverser->traverse($parser->parse($code));
        }
    }
}

Parser::parse();
```
Am I doing something wrong? Can I somehow workaround the issue to be able to parse these functions declarations? Is it possible to adapt parser to properly parse declarations of functions `exit` and `die` in stubs? 
Thank you in advance!

**Comment by nikic** [comment]
The problem here is that while PHP 8.4 makes exit/die into functions, they still have special parsing where `exit` and `die` are keywords, not plain identifiers. As such, something like `function exit() {}` is not valid PHP code. An earlier version of https://wiki.php.net/rfc/exit-as-function actually proposed to change this and remove the `exit`/`die` keywords, but the final version went in a different direction.

I could allow these as function names as a special case, similar to how readonly is allowed: https://github.com/nikic/PHP-Parser/blob/3abf7425cd284141dc5d8d14a9ee444de3345d1a/grammar/php.y#L467C1-L470

This would not match what PHP does, but I wouldn't mind adding the special case if it makes things easier for you.

**Comment by isfedorov** [comment]
If in this case I'll be able to get a function name, function parameters and function return type using the parser then yes, such workaround will fix the issue.

**Comment by ondrejmirtes** [comment]
Joining here because it'd help me a lot if PHP-Parser was able to parse these stubs. I actually opened a duplicate (https://github.com/nikic/PHP-Parser/issues/1036) by mistake.

**Comment by nikic** [comment]
Also submitted https://github.com/php/php-src/pull/16308 to drop the workaround in php-src.
