### ISSUE TITLE
Incorrect file positions when source has special characters

### ISSUE THREAD

**Issue by dpb587** [nikic/PHP-Parser#169]
Hi - I've run into an issue when parsing source code with special characters (e.g. `ü`), specifically when using the `startFilePos` and `endFilePos` attributes. Here's my test case which simply parses the problematic source, and then shows where the second constant is considered to be:

    <?php require_once 'vendor/autoload.php';
    
    $code = '<?php const C1 = "ümlaüt"; const C2 = "plain";';

    $parser = new \PhpParser\Parser(
        new \PhpParser\Lexer(
            [ 'usedAttributes' => [ 'startFilePos' , 'endFilePos' ] ]
        )
    );

    $nodes = $parser->parse($code);
    
    echo $code . "\n"
       . str_repeat(' ', $nodes[1]->getAttribute('startFilePos'))
       . str_repeat('^', $nodes[1]->getAttribute('endFilePos') - $nodes[1]->getAttribute('startFilePos'))
       . "\n"
       ;

When I run the test it results in:

    <?php const C1 = "ümlaüt"; const C2 = "plain";
                                 ^^^^^^^^^^^^^^^^^^

Which is off by two from what I expect. If I change [`lib/PhpParser/Lexer.php`](https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Lexer.php#L161-L162) from using `substr_count` and `strlen` to `mb_substr_count` and `mb_strlen`, it seems to fix it:

    <?php const C1 = "ümlaüt"; const C2 = "plain";
                               ^^^^^^^^^^^^^^^^^^

I was going to do a pull request, but then I wasn't sure if this requires some sort of backward compatibility? Is multibyte always included now? Or does PHP-Parser still run on older versions where it isn't necessarily included? Is there a simpler/alternative solution to `mb_*`? So, I figured I'd ask if you had some feedback or further insights into this first.

If it's relevant, my environment I was testing this on:

    $ sw_vers
    ProductName:	Mac OS X
    ProductVersion:	10.10.1
    BuildVersion:	14B25
    
    $ php -v
    PHP 5.6.2 (cli) (built: Nov  2 2014 09:34:41) 
    Copyright (c) 1997-2014 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
        with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
        with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans    

Thanks for your help on this (and for creating PHP-Parser)!

**Comment by nikic** [comment]
The file offsets are byte offsets yes. I won't be switching to codepoint offsets, because this would (apart from being a PITA in general) require actually knowing the encoding of the source file, which is something that is not generally known and cannot be reliably guessed.

I would recommend you to convert the byte offsets into codepoint offsets using your knowledge of the used encoding. It doesn't look like PHP has a function to do this directly, so a combination of `mb_strcut` with `mb_strlen` should do:

    $cpOffset = mb_strlen(mb_strcut($code, 0, $byteOffset));

If you want to use grapheme cluster offsets instead (which may be more appropriate as the umlauts may be created using combining marks) you could use `grapheme_extract` with `GRAPHEME_EXTR_MAXBYTES` in combination with `grapheme_strlen`. This of course assumes that your code is in UTF-8.

    $gcOffset = grapheme_strlen(grapheme_extract($code, $byteOffset, GRAPHEME_EXTR_MAXBYTES));

**Comment by dpb587** [comment]
Well that's confusing [to me]. I appreciate the details though - it definitely points me in the right direction on what I need to learn more about and try. Thanks!
