### ISSUE TITLE
Request: generated PHP identical to parsed PHP

### ISSUE THREAD

**Issue by garfix** [nikic/PHP-Parser#179]
Thanks for writing this library. I want to use it to refactor our large code base, by changing existing syntactic structures to new ones. For example I would like to change some global variables to static factory calls.

My point is that I want that the code I do not need to touch will remain the exact same. This means that if the parse tree is pretty printed, that even the whitespace is identical to the input.

I checked the code to see if I could make this change myself, but it looks pretty complicated.

Would it be possible to add this feature. I think it would be useful to others as well.

greetings!

**Comment by nikic** [comment]
This is an often requested feature (see also #41), but it's pretty hard to implement format-preserving transformations in a generic way. I don't see this being implemented anytime soon :/

The approach I am currently using for this purpose is to make modifications based on token positions (see https://github.com/nikic/PHP-Parser/blob/master/doc/component/Lexer.markdown#using-token-positions). I.e. using the AST I find what places need to be changed and then do the changes in the token array. (Alternatively you can use file positions and directly replace the code rather than replacing tokens.)

**Comment by garfix** [comment]
Thanks, Nikic, I understand why this is hard to implement, and your alternative will work just fine for me. :)
