### ISSUE TITLE
Why cloning nodes in NodeTraverser?

### ISSUE THREAD

**Issue by mnapoli** [nikic/PHP-Parser#184]
Hi there!

I was using the NodeTraverser to create links between nodes (e.g. link a method to its class). I painfully realized that the traverser would [clone each node when traversing](https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/NodeTraverser.php#L68), which means it would mess up all links between nodes.

I was wondering why it is implemented that way? I have temporarily implemented my own traverser that doesn't clone nodes, but maybe there's an important reason you made it work that way?

**Comment by nikic** [comment]
It's been a while ... I think the `clone` is there because conceptually the traverser is supposed to take one AST and return a new one, which is independent from the original.

In hindsight this was probably a bad idea, given how the traverser is normally used to replace the orginal (`$stmts = $traverser->traverse($stmts)`). But I don't think this can be changed at this point.

**Comment by mnapoli** [comment]
OK thanks, what I could do is add a new implementation of the `NodeTraverserInterface` that doesn't clone nodes?

I'm afraid I would have to duplicate a few lines of code (even if I extend `NodeTraverser`) but at least it would be there for people to use.

**Comment by nikic** [comment]
Maybe add a flag to the ctor that allows skipping the clone?

**Comment by mnapoli** [comment]
Well that makes much more sense for such a simple stuff, you are right.

I opened a PR here: #186
