### ISSUE TITLE
Trying to use Lexer by itself, token IDs don't match PHP T_* constants.

### ISSUE THREAD

**Issue by rulatir** [nikic/PHP-Parser#204]
When I try to use the Lexer by itself, the token IDs don't match the PHP T_* constants. For example, the value of T_CONSTANT_ENCAPSED_STRING is 318 on my system, but when Lexer scans the token of that type, the return value is 320.

Using PHP 5.6.

**Comment by aik099** [comment]
Maybe that constant value was changed at some point PHP, but lexer using old value.

**Comment by nikic** [comment]
The lexer return values refer to the class constants defined in `https://github.com/nikic/PHP-Parser/blob/1.x/lib/PhpParser/Parser.php#L30` (which have the same names as the corresponding PHP constants). This can't match up with PHP values because those vary between different versions anyway.

Why are you using the lexer by itself though? It's just a thin wrapper around the native token_get_all().
