### ISSUE TITLE
Generator for a code generator

### ISSUE THREAD

**Issue by vandroids** [nikic/PHP-Parser#211]
1). While writing some code-generation code I found myself constantly crawling through /lib/ and /test/ directories of PhpParser looking for examples of building blocks to make the desired code.

So I thought that it could be nice to have a method in parser which allows you to get the "generating" code for current AST.

It's like the reverse of this example https://github.com/nikic/PHP-Parser/blob/1.x/doc/4_Code_generation.markdown

The profit here is that we can take any desired code example and receive (as a complete source code ready to use) all PhpParser instructions that we need to create such code (without searching for documentation or examples). Sort of a "self-documenting" feature for a code generation process :)

2). Off-topic
Also it may be worth to add some navigation capabilities to classes/traits/whatever:
```
    $method = $class->findMethod( $method_name );
    $property = $class->findProperty( $property_name );
```
because now if I want to, let's say, get an access to class constructor I have to do something like this:
```
    $constructor = array_reduce( $class->getNode()->stmts, function( $carry, $item ){
        if( !$carry && get_class( $item ) == 'PhpParser\Node\Stmt\ClassMethod' && $item->name == '__construct' )
        {
	        $carry = $item;
        }
        return $carry;
    });
```
I don't know how useful or relevant are these thoughts for your project. So excuse me if "Issues" is not an appropriate place for such conversation.

**Comment by nikic** [comment]
1) It would be relatively complicated to do this (especially generating the builder code), I don't think it's worth the effort.

The most important part when doing codegen is a) having a good IDE (= PhpStorm) and b) knowing how nodes are called (e.g. via a node dump). 

2) I've just added a `ClassLike::getMethod($name)` method (returning null if not found). With properties there's currently the issue that `public $foo, $bar;` has one node for the whole declaration and two separate ones for `$foo` and `$bar`. Just returning the inner nodes is not useful in many cases because they lack visibility information.

**Comment by vandroids** [comment]
Ok. Thanks for support!
