### ISSUE TITLE
Invalid octal literals ok even with ONLY_PHP7

### ISSUE THREAD

**Issue by afraca** [nikic/PHP-Parser#256]
Hi, 

Thanks for your work on this package.

Per the 7.0 migration guide:

>  Previously, octal literals that contained invalid numbers were silently truncated (0128 was taken as 012). Now, an invalid octal literal will cause a parse error. 

I expect parsing in PHP7 only mode to fail
`        $this->parser = (new ParserFactory)->create(ParserFactory::ONLY_PHP7);`

Now we simply get
`object(PhpParser\Node\Scalar\LNumber)[6]
          public 'value' => int 10
          protected 'attributes' => 
            array (size=3)
              'startLine' => int 3
              'endLine' => int 3
              'kind' => int 8`

**Comment by nikic** [comment]
This is how implemented with https://github.com/nikic/PHP-Parser/commit/e7869b9f1457e4756649bd40d7d5ce67883b7f9b.

Note that generally speaking, PHP-Parser does not makes sure that code is actually valid PHP code, it only ensures that it is syntactically valid and does only a few checks on top of that. I'm including this particular error because it's lexical in nature and it's not possible to detect it from the generated AST.

**Comment by afraca** [comment]
Actually Nikita, this is a syntactic issue. I'm not really sure how official the php-langspec is, but:
https://github.com/php/php-langspec/blob/master/spec/09-lexical-structure.md#general-2

> octal-literal::
      0
      octal-literal   octal-digit

(Where octal digit is self-explanatory)
