### ISSUE TITLE
Parser throws lexer errors despite throwOnError = false

### ISSUE THREAD

**Issue by MadHed** [nikic/PHP-Parser#306]
First off, great library! We are using it in the php language server project for VS Code.

I believe there is a bug in ParserAbstract::parse() or at least an inconsitency with its documentation.

The lexer throws when it encounters an error but this exception is never caught in the parser despite throwOnError being set to false.

This happened to me while editing a source file and starting a block comment. The parser throws an error with "PHP Warning:  Unterminated comment starting line ..."

Should the exception not be caught in this case and added to the error array? The tokens up to the error are available and could be parsed.

**Comment by nikic** [comment]
Implemented by (mostly) https://github.com/nikic/PHP-Parser/commit/c79ea6d1d3f1caa75e304226faa919a9ca866c01. I've completely rewritten the lexer error handling, so that lexer errors now have precise offset information, there can be multiple lexer errors and we can continue parsing in the presence of lexer errors.

**Comment by MadHed** [comment]
awesome
