### ISSUE TITLE
Error recovery with members and keywords

### ISSUE THREAD

**Issue by Gert-dev** [nikic/PHP-Parser#383]
Hello

In the light of the recent tickets relating to error recovery, I wanted to report an additional case that is rather hard for me to work around in the hopes that it is possible for php-parser to somehow recover from it:

```php
<?php

$this->

if (true) {

}
```

It is, in fact, an incomplete property fetch or method call with a missing semi-colon that happens to be followed by a PHP keyword.

php-parser currently generates the following error:

```
====> File /home/me/Downloads/Test.php:
Syntax error, unexpected '}' on line 7
==> Node dump:
array(
)
```

Also, a bit off-topic, but I wanted to take this opportunity to commend you for your continued work on this project. In particular, the upcoming changes related to identifier nodes will allow me to properly fetch the range of the last part of method calls and other nodes (as these were previously strings, this information was not present).

Thanks in advance

**Comment by nikic** [comment]
This is an unfortunate combination of two factors:

 * In PHP a reserved keyword directly following `->` will be treated as an ordinary identifier (already at the lexer level).
 * PHP has an alternative array access syntax `$foo{$bar}`.

Together, these mean that PHP-Parser will try to parse this as `$this->if(true){$someExpr}` until it reaches an error when it turns out the `{}` block is does not contain a well-formed expression. At this point it's no longer possible to recover in a meaningful way (the best we might do with additional error recovery rules is to keep a `$this->if(true);` call.)

I think the best solution here would be a custom lexer that finds sequences T_OBJECT_OPERATOR T_WHITESPACE T_STRING, where the T_WHITESPACE contains a newline and the T_STRING is a reserved keyword, and converts the T_STRING into the appropriate keyword token. This should enable recovery to work as normal. Of course it will no longer be fully accurate, as for example

```php
<?php

$this->

if (true)
    [123];
```

would then be parsed to an incomplete property access and an if statement, rather than the call `$this->if(true)[123];` it is under PHP semantics.

**Comment by nikic** [comment]
Or a more radical solution, insert an implicit semicolon after T_OBJECT_OPERATOR followed by T_WHITESPACE with a newline. This strays further from technical semantics, but will probably be closer to the output you want to see if you have something like

```php
$this->
$this->foo();
```

Which is currently parsed as `$this->$this->foo()`. Technically correct, but not the most useful output.

**Comment by Gert-dev** [comment]
That makes sense. Since it's not an issue that's easy to solve for php-parser, I'll look into investigating a manual fix for this at some point in the future in my codebase. Thanks for the information!
