### ISSUE TITLE
Invalid trailing element on list() with a trailing comma

### ISSUE THREAD

**Issue by j-d** [nikic/PHP-Parser#387]
When parsing this code:

```php
<?php

list(
    $a, 
    $b, 
) = array(1, 2);
```
The resulting `List_` expression has three items, two ArrayItems as expected and one null which should not be there.

According to the documentation, the `items` attribute of a `List_` object should be `ArrayItem[]`, and not `ArrayItem[]|null[]` (See https://github.com/nikic/PHP-Parser/blob/a32e3797d411590841ae06dd559ddb867d376aff/lib/PhpParser/Node/Expr/List_.php#L9 )

That snipped is a valid PHP syntax as per https://3v4l.org/lrLXN

Thanks for your hard work.

**Comment by nikic** [comment]
The type annotation is incorrect -- it should be `(List_|null)[]`, because `list($a,,,,$b)` is valid and will be represented by nulls.

I'm not sure whether a trailing null should be present in this case. The background here is that while in `array(1, 2, )` the last comma is a trailing comma, while in `list($a, $b, )` the last comma is an element-skip. However, the representation is inconsistent here, so it might be preferable to drop one trailing null.

**Comment by j-d** [comment]
Good points. Thanks for your prompt response.
Maybe just add null to the type annotation and that will be enough. My issue was that I was not expecting to find null after seeing `ArrayItem[]` [here](https://github.com/nikic/PHP-Parser/blob/a32e3797d411590841ae06dd559ddb867d376aff/lib/PhpParser/Node/Expr/List_.php#L9).

**Comment by nikic** [comment]
I've fixed the type annotation in https://github.com/nikic/PHP-Parser/commit/4e162bd0eae5acd019bcb619c1328507c763bbe0.

**Comment by j-d** [comment]
Thanks
