### ISSUE TITLE
Convert JSON back into a node tree

### ISSUE THREAD

**Issue by limeblack** [nikic/PHP-Parser#401]
Has anyone made any headway on converting JSON back into a node tree or alternatively code(and then back to the AST)?

Alternative is there another format alternatively maybe XML that I convert back and forth between?
Having only PHP isn't completely useful.
It says 

>Furthermore, not all ASTs can be JSON encoded.

What is an example of such?

**Comment by nikic** [comment]
I used to support XML serialization and deserialization (in fact still supported in the current stable version 3.x), but dropped this in the current development branch, because nobody seems to be using it and I can't imagine anyone wanting to use it (XML is quite atrocious for this purpose, see the [example dump](https://github.com/nikic/PHP-Parser/blob/3.x/doc/3_Other_node_tree_representations.markdown#serialization-to-xml)...)

The ability to convert JSON back into a node tree should be added. It should not be particularly hard either.

As far as I know, there are exactly two reasons why JSON encoding may not be possible: The first is that the AST contains a string that is not well-formed UTF-8. The second is that it contains an INF value (which can happen if the code contains something like `1e1000`).

**Comment by limeblack** [comment]
I'm afraid you are probably right that trying to modify the XML myself is pretty crazy.
Your advice is solid.  Nice to see you around SO.

I have been reading through your tests and docs.  Now that you mentioned it I see the serialize function.
Do you mind directing me to where an example of converting XML to php code?  I have found this example in the docs but its not quite there.  I will likely close this issue soon.

```php
$xml2 = <<<XML
<?xml version="1.0" encoding="UTF-8"?>
<AST xmlns:scalar="http://nikic.github.com/PHPParser/XML/scalar">
 <scalar:array>
  <scalar:array></scalar:array>
  <scalar:array/>
  <scalar:string>test</scalar:string>
  <scalar:string></scalar:string>
  <scalar:string/>
  <scalar:int>1</scalar:int>
  <scalar:float>1</scalar:float>
  <scalar:float>1.5</scalar:float>
  <scalar:true/>
  <scalar:false/>
  <scalar:null/>
 </scalar:array>
</AST>
XML;
$result = array(
	array(), array(),
	'test', '', '',
	1,
	1, 1.5,
	true, false, null
);

$unserializer  = new PhpParser\Unserializer\XML;
print_r($unserializer->unserialize($xml));
```

**Comment by nikic** [comment]
A JSON decoder has been implemented in https://github.com/nikic/PHP-Parser/commit/9373a8e9f551516bc8e42aedeacd1b4f635d27fc.

A full round-trip from PHP code to PHP code would go something like this now:

```php
$code = ...;

$parser = (new PhpParser\ParserFactory)->create(PhpParser\ParserFactory::ONLY_PHP7);
$stmts = $parser->parse($code);
$json = json_encode($stmts);

// Do stuff

$jsonDecoder = new PhpParser\JsonDecoder;
$stmts = $jsonDecoder->decode($json);

$prettyPrinter = new PhpParser\PrettyPrinter\Standard;
$code = $prettyPrinter->prettyPrintFile($stmts);
```
