### ISSUE TITLE
Optionally add nodes for whitespace

### ISSUE THREAD

**Issue by fabpot** [nikic/PHP-Parser#41]
I don't know if that's part of the scope of PHP-Parser, but it would be useful (at least for me as it would greatly simplify the code for my PHP CS fixer -- http://cs.sensiolabs.org/) to be able to have nodes for whitespace. This should probably be an option as most of the time, you don't care about whitespace, and also because it would add many nodes.

**Comment by joshuaspence** [comment]
+1

**Comment by funivan** [comment]
:+1:

**Comment by funivan** [comment]
`echo 1 + 1 `
```
EchoStmNode
  WhiteSpaceNode
  Number
  WhiteSpaceNode
  Plus
  WhiteSpaceNode
  Number
```
To pretty print this code you need go through all nodes and join their value. 
Lets go future:

```
EchoStmNode  => echo
  WhiteSpaceNode => '  '
  Number => 1
  WhiteSpaceNode => '\n\n'
  Plus => +
  FunctionCall => count
    Symbol => (
    WhiteSpaceNode => '   '
    Variable => $items
    Symbol => )
  Semicolon => ;
```
This code will be represented as:
```php
echo 1

+count(  $items);
```
White spaces goes inside node. 
All modern ides use AST tree. So we can watch for their representation of Php code in AST. (Eclipse, PhpStorm, etc ..)

**Comment by romaincanon** [comment]
Hey, I'd also be very interested in a solution for this issue.

I understand the actual structure is not made to support this, I just want you to know at least one more person is interested. :-)

Have a great day, and thanks for your work!

**Comment by lisachenko** [comment]
Any news for this issue? I wonder, will it be possible to use column+line information from each node instead of introducing a Whitespace node? Then printer will fill empty spaces, for example, for `echo  1 + 2` it can check that `1` has position 7, so instead of single whitespace, it will produce two spaces, then checks next token `+` and add one more space, etc...

So, currently available attributes `startTokenPos`, `endTokenPos`, `startFilePos`, `endFilePos` can give all information to reconstruct the original source code with formatting and spacing. Not sure about tab character...

**Comment by nikic** [comment]
@lisachenko What I'm doing nowadays is use the AST to do analysis and figure out where things are, but do modifications on the source code (or the tokens) directly. You need some way to queue modifications (e.g. https://github.com/nikic/TypeUtil/blob/master/src/MutableString.php) and then this works pretty well for doing smaller changes based on startFilePos and endFilePos. Obviously this becomes a bit more tricky for larger changes.

As to making use of file/token offsets in the pretty printer, I gave that a try some time ago (https://gist.github.com/anonymous/4365484 linked above). I remember that the implementation was nowhere near robust enough. With enough effort one can probably get it to work (but I won't be working on it).

**Comment by lisachenko** [comment]
@nikic thank you for sharing your thoughts, I'll give a try for your pretty printer, it may suite my needs. Actually, I don't need an exact formatting, only to preserve line numbers, otherwise IDE shows crazy break points in the docblocks, statements and empty spaces ;)
Just combined AST, PHP stream wrapper and stream filter with node visitors to transform PHP source code on the fly. AST hook on userland side looks pretty good.

**Comment by webmozart** [comment]
@nikic Maybe you should close this issue then and add some docs about how to solve this :)

**Comment by YuriyNasretdinov** [comment]
For our soft mocks project we implemented a hack for the stock pretty-printer that allowed to most preserve all line numbers except for all kinds of braces because there literally is no line number information about these tokens.

The first part of the code consists of the following and it should work with current versions without major issues:

```
class SoftMocksPrinter extends \PhpParser\PrettyPrinter\Standard
{
    private $cur_ln;
    /**
     * Pretty prints an array of nodes (statements) and indents them optionally.
     *
     * @param \PhpParser\Node[] $nodes  Array of nodes
     * @param bool   $indent Whether to indent the printed nodes
     *
     * @return string Pretty printed statements
     */
    protected function pStmts(array $nodes, $indent = true)
    {
        $result = '';
        foreach ($nodes as $node) {
            $row = "";
            $cur_ln = $this->cur_ln;
            $comments = $this->pComments($node->getAttribute('comments', array()));
            $this->cur_ln += substr_count($comments, "\n");
            if ($node->getLine() > $this->cur_ln) {
                $row .= str_repeat("\n", $node->getLine() - $this->cur_ln);
                $this->cur_ln += substr_count($row, "\n");
            }
            $row .= $comments
                . $this->p($node)
                . ($node instanceof \PhpParser\Node\Expr ? ';' : '');
            $this->cur_ln = $cur_ln + substr_count($row, "\n"); // get rid of cur_ln modifications in deeper context
            $result .= $row;
        }
        if ($indent) {
            return preg_replace('~\n(?!$|' . $this->noIndentToken . ')~', "\n    ", $result);
        } else {
            return $result;
        }
    }
    public function prettyPrintFile(array $stmts)
    {
        $this->cur_ln = 1;
        $this->preprocessNodes($stmts);
        return "<?php " . str_replace("\n" . $this->noIndentToken, "\n", $this->pStmts($stmts, false));
    }
    protected function p(\PhpParser\Node $node)
    {
        $prefix = '';
        if ($node->getLine() > $this->cur_ln) {
            $prefix = str_repeat("\n", $node->getLine() - $this->cur_ln);
            $this->cur_ln = $node->getLine();
        }
        return $prefix . $this->{'p' . $node->getType()}($node);
    }
```

The other part is removing all "\n" from pSmth() functions so that we manually control all whitespace characters.

The problem, obviously, is with this "other part" because it requires writing fragile code that is just a copy of all parent functions. We could not just make calls to parent methods and remove all "\n"'s because functions are recursive.

So I would suggest adding some code into PHP-Parser that would allow some kind of line-preserving pretty-printing by adding possibility to get rid of "\n"'s everywhere (e.g. move "\n" to a public propertly that could be redeclared to be "")

**Comment by lisachenko** [comment]
@nikic @YuriyNasretdinov All Java tools (for example, IDEA) has a special node-type for storing an information about whitespaces, so it would be nice to follow this. But this should be an optional feature for Parser - to capture whitespaces as an AST-nodes. This will increase the complexity of AST-walking, but will give a control over file positions for different elements.

**Comment by jails** [comment]
Just wondering if this is issue has been addressed in the 3.x version since all comments seems to be older than 6 months ?

**Comment by nikic** [comment]
@jails Nope, no changes here.

**Comment by nikic** [comment]
So, I've given this problem (format-preserving pretty prints) another shot and I have a viable prototype now: https://github.com/nikic/PHP-Parser/compare/formatPreservingPrint (based on #322)

The implementation does not add whitespace nodes in the AST, instead we try to reconstruct the original formatting based on token offset information.

Here is a usage example:

```php
$lexer = new Lexer\Emulative([
    'usedAttributes' => [
        'comments',
        'startLine', 'endLine',
        'startTokenPos', 'endTokenPos',
    ],
]);
$parser = new Parser\Php7($lexer, [
    'useIdentifierNodes' => true,
    'useConsistentVariableNodes' => true,
    'useExpressionStatements' => true,
    'useNopStatements' => false,
]);

$traverser = new NodeTraverser();
$traverser->addVisitor(new NodeVisitor\CloningVisitor());

$printer = new PrettyPrinter\Standard();

$oldStmts = $parser->parse($code);
$oldTokens = $lexer->getTokens();

$newStmts = $traverser->traverse($oldStmts);
// MODIFY $newStmts HERE

$newCode = $printer->printFormatPreserving($newStmts, $oldStmts, $oldTokens);
```

The important bits here are a) that you need to specify a bunch of non-standard options to avoid BC breaks until PHP-Parser 4.0, b) a CloningVisitor is run before any changes, so we retain the original AST as a reference and c) we also need the old tokens from the lexer.

The whole thing isn't well tested yet, so likely going to be many issues depending on which part of the AST you try to modify. There's a couple of limitations as to where we can preserve formatting and where we can't:

 * Changes to non-Node subnodes results in formatting being lost. The reason is that we don't have offset information for non-Node subnodes. Some of the parser options specified above (e.g. useIdentifierNodes) make use of Nodes where previously strings were used. For example, this allows changing the name of a function while preserving formatting. On the other hand changing a function to return by ref (this is a boolean subnode) will drop formatting.
 * We can preserve formatting if an item in an array subnode is replaced, but not if an item is removed or added. We can do better here, but this will require a good bit of work (would probably need something like an array differ).
 * Formatting for anon classes is lost, because the attribute assignment in this case is too weird right now.

**Comment by nikic** [comment]
Here a complete example: https://gist.github.com/nikic/3229644ada5576622d7d538f6bff2098
This is basically https://github.com/Roave/FunctionFQNReplacer, but preserving formatting.

**Comment by nikic** [comment]
Closing this in favor of #344, which contains remaining TODOs for this.

**Comment by rentalhost** [comment]
Instead of create a new `T_WHITESPACE`, it is not possible add it directly to the next node like "comments" does? Something like:

```php
$lexer = new PhpParser\Lexer([ 'usedAttributes' => [ 'whitespaces' ]]);
```

```
Expr_FuncCall(
    ...
    attributes: {
        whitespaces: "\s\s\s\s\s\s\r\n\t\t\s\s"
    }
)
```
