### ISSUE TITLE
Could the Standard pretty printer add a space after "use" keyword

### ISSUE THREAD

**Issue by martinsik** [nikic/PHP-Parser#418]
I've noticed that when I try to pretty print code with `PhpParser\PrettyPrinter\Standard` that contains closures with the `use` clause it'll be printed without spaces after the `use` keyword:

    function() use($var) { ...

while I'd expect this:

    function() use ($var) { ...

I checked the documentation (http://php.net/manual/en/functions.anonymous.php) and they do use spaces after `use` so I was thinking if this is intentional or possibly available for PR.

https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/PrettyPrinter/Standard.php#L556

**Comment by nikic** [comment]
We can't really satisfy everyone with the default behavior -- there's just too many different coding styles in active use. Even adding options is not feasible, because there are hundreds of individual items that may need configuration. My recommendation would be:

 * If you only want to adjust a few things, extend the respective method in the pretty printer.
 * If you want to have more precise control of the formatting, print using the default style and then run the result though one of the existing code formatting libraries, which already implement fine-grained options to control formatting.
 * If you're not generating but modifying code, #344 may be an option.
