### ISSUE TITLE
How to add node at the end nested property 

### ISSUE THREAD

**Issue by TomasVotruba** [nikic/PHP-Parser#431]
I have following code:

```php
$this->someProperty->anotherProperty[]->lastProperty;
```

**And I need to add `MethodCall` to the last item**:

```php
$this->someProperty->anotherProperty[]->lastProperty->getValue();
```

When I do something like this:

```php
public function enterNode(Node $node) 
{
    // $this->someProperty->anotherProperty[]->lastProperty
    return new MethodCall($lastPropertyNode, 'getValue');
}
```

**it will end with segfault**.

I tried nulling `origNode` and `parentNode` in the whole tree, but no effect.

I feel like I need to recreate whole expression for all properties that are in this line. It worked for simple cases at least, but I don't want to do so much manual work.

Any ideas?

**Comment by nikic** [comment]
I can't reproduce this issue. The following orig/change/expected test succeeds:

```
<?php
$this->someProperty->anotherProperty[]->lastProperty;
-----
$stmts[0]->expr = new Expr\MethodCall($stmts[0]->expr, 'getValue');
-----
<?php
$this->someProperty->anotherProperty[]->lastProperty->getValue();
```

If you're seeing a segmentation fault, the most likely cause is infinite recursion. Could you try running it through xdebug with a reasonable recursion limit (say 2000) and see whether (and where) it generates a recursion error?

I suspect that you're creating a circular AST.

**Comment by TomasVotruba** [comment]
I suspect that too, your syntax look very nice. I want to try your approach, but don't know how to manage my current code.

**I need to match `VarNode` of specific type in the whole expression.**

At the moment I do it like this: https://github.com/RectorPHP/Rector/blob/9c74e03d8c2015d00c6c426fcf27602b76524625/src/Rector/Contrib/PhpParser/IdentifierRector.php

I might try something like this, but I'm affraid of performance:

```php
if (! $node instanceof Expression) {
    return false;
}

$variableNode = $nodeFinder->find($node, function ($node) {
    if ($this->isVariableOfType($node)) { // an existing service that knows that
          return $node;
    }
});

if ($variableNode === null) {
    return $node;
}

return new Expression(new Expr\MethodCall($node->stmts[0], 'getValue'));
```

What do you think?

**Comment by TomasVotruba** [comment]
Slowly getting there. I have tried:

```php
return new Expression(
    new MethodCall($expressionNode->expr, 'toString')
);
```

but output is bit weird:



```diff
'<?php declare(strict_types=1);\n

 \n
 $constNode = new \PhpParser\Node\Const_;\n
-$name = $constNode->name->toString();\n
+($name = $constNode->name)->toString();\n
```



Here is full code:

https://github.com/RectorPHP/Rector/blob/php-parser-segfaults-and-extra-spaces/src/Rector/Contrib/PhpParser/IdentifierRector.php#L61-L97

**Comment by nikic** [comment]
The new code doesn't make a lot of sense, because you're adding the method call on the entire expression (including the assignment) rather than on the property fetch.

Can you point me to a commit where it's possible to reproduce this issue? I've checked out the `php-parser-segfaults-and-extra-spaces` branch, but don't get segfaults there. Only many failures related to better-reflection incompatibility.

**Comment by TomasVotruba** [comment]
It is this test: https://github.com/RectorPHP/Rector/blob/php-parser-segfaults-and-extra-spaces/tests/Rector/Contrib/PhpParser/IdentifierRector/Test.php

File 4

**Comment by nikic** [comment]
For me this test fails with:

> TypeError: Argument 1 passed to Rector\BetterReflection\SourceLocator\Reflection\SourceStubber::addDocComment() must be an instance of PhpParser\BuilderAbstract, instance of PhpParser\Builder\Interface_ given, called in /home/nikic/Rector/vendor/rector/better-reflection/src/SourceLocator/Reflection/SourceStubber.php on line 63

**Comment by TomasVotruba** [comment]
I see. I've tagged the forked packages and merged this PR to master.

The error should be clear now:
https://travis-ci.org/RectorPHP/Rector#L594

**Comment by nikic** [comment]
I was able to fix this by reverting https://github.com/RectorPHP/Rector/commit/0293adc2d4f7da81658f841fa7e008e8e1056543 and changing the `refactor` implementation to:

```php
        $parentNode = $propertyFetchNode->getAttribute(Attribute::PARENT_NODE);
        if ($parentNode instanceof MethodCall) {
            return $propertyFetchNode;
        }

        $call = new MethodCall($propertyFetchNode, 'toString');
        $propertyFetchNode->setAttribute(Attribute::PARENT_NODE, $call);
        $call->setAttribute(Attribute::PARENT_NODE, $parentNode);
        return $call;
```

This updates the parent node attribute to match the new structure.

As to why this happens: The segfault doesn't occur due to recursion over cyclic structure, but rather during GC traversal of a very deeply nested structure. The issue is that if a visitor returns a new node from `enterNode`, its children will still be visited as usual. So refactor() will again be invoked on the property fetch within the new method call. Because the parent nodes were not up to date, the check for the already existing method call did not trigger, so it ended up nesting more and more method calls.

I never noticed this potential pitfall before, because I generally only modify nodes during leaveNode. I'm not sure what the best way to address this is, both from your and my side. I tried modifying `AbstractRector` both to use `leaveNode` and to use a split like this: https://gist.github.com/nikic/97ed25680c502751c769bbc9dcfb468e. However, both variants had test failures. So it looks like some rectors do need the behavior where the subnodes of the new node are still visited.

**Comment by TomasVotruba** [comment]
Oh, now it's so obvious with the parent node update. Thanks for explaining.

Also thanks for the commit refernce, it was much easier to implement your suggestion with that. And it works very nicely.


As for `leaveNode()`, I've chosen it, because it was the first from the top and I didn't know a difference between them. So I'm open to any suggestions.
