### ISSUE TITLE
Method for comparing equality of Nodes

### ISSUE THREAD

**Issue by emmetog** [nikic/PHP-Parser#473]
I'm comparing two different nodes of type `PhpParser\Node\Stmt\ClassMethod` but I've noticed that if both are exactly the same except for a different capitalization of the method name then the methods are _not_ the same. In PHP capitalization of method names is ignored and so these two methods should be "the same" when compared against each other.

```php
$one = new PhpParser\Node\Stmt\ClassMethod('testName');
$two = new PhpParser\Node\Stmt\ClassMethod('testname');

// Returns false, even though the two methods are "equal"
var_dump($one == $two);
```

I propose adding a method called `equals($other)` to these nodes which can be used to determine if one node is equal to another (after smoothing out how PHP ignores case in some situations and other possible differences).

We can create a new `Equatable` interface in this library or we can use an already existing one, for example [litgroup/equatable](https://github.com/LitGroup/equatable.php), I'll leave that up to you to decide.

Would this be something that you would consider accepting if I submit a PR? (I can write extensive tests to test this functionality too)

**Comment by nikic** [comment]
I think this would be out of scope of this library, because there are varying degrees of equality you could be going for. E.g. if you consider `public function foo(){}` and `public function FOO(){}` the same, then which of the following would be considered the same as well?

```php
public function foo() {
    $foo = 1; return $foo;
}
public function foo() {
    $foo = 1;
    return $foo;
}
public function foo() {
    $f = 1;
    return $f;
}
public function foo() {
    return 1;
}
```

They are all functionally identical, but will probably not be considered "equal" in many contexts. I think there is no correct answer to this question, so from my point of view an implementation of some specific equality relation would be better suited for a 3rd party library.

**Comment by emmetog** [comment]
Ok, thanks for the feedback @nikic
