### ISSUE TITLE
[4.0] Why is Param::$var a Variable?

### ISSUE THREAD

**Issue by ondrejmirtes** [nikic/PHP-Parser#481]
Hi,
previous `Param::$name` (string) has been changed to `Param::$var` which contains a Variable instance. Since Variable::$name can contain Expr or string, is there any actual situation where `Param::$var::$name` can be an Expr? If not, I don't understand the reasoning behind this change since this makes writing strictly-typed code harder.

**Comment by nikic** [comment]
There are two reasons why `Param` and a number of other places have been changed to use a `Variable` node:
 * Consistency: If something is a variable, it should always be represented by a `Variable` node rather than a string.
 * Attributes: We want to have accurate position information for all nodes, which is not possible with a raw string.

The second concern could be resolved by using a `VarLikeIdentifier`, the first concern is why I prefer `Variable` here.

I'm not really familiar with phpstan, is it able to handle things like `assert(is_string($param->var->name))` for the purposes of type analysis?

**Comment by ondrejmirtes** [comment]
OK, thanks for explaining! Yes, it's possible to eliminate possible types before passing the value to another place which I'll do 😊
