### ISSUE TITLE
Nop endLine doesn't look right

### ISSUE THREAD

**Issue by j-d** [nikic/PHP-Parser#483]
I am using 4.0

In this example:

```
<?php

$a = 1;

// A comment
```

The `Nop` statement, will have `startLine` = 6 and `endLine` = 3.

Maybe the fix is as easy as `max(startLine, endLine)` when it is created, but I don't know enough. 

Thanks for your hard work.

**Comment by tomzx** [comment]
In `Lexer::getNextToken`

https://github.com/nikic/PHP-Parser/blob/e4a54fa90a5cd8e8dd3fb4099942681731c5cdd3/lib/PhpParser/Lexer.php#L243

`$token` is an array

https://github.com/nikic/PHP-Parser/blob/e4a54fa90a5cd8e8dd3fb4099942681731c5cdd3/lib/PhpParser/Lexer.php#L253

the value of the pointed drop token is set

https://github.com/nikic/PHP-Parser/blob/e4a54fa90a5cd8e8dd3fb4099942681731c5cdd3/lib/PhpParser/Lexer.php#L264

thus the else block is executed

https://github.com/nikic/PHP-Parser/blob/e4a54fa90a5cd8e8dd3fb4099942681731c5cdd3/lib/PhpParser/Lexer.php#L276

and the continue returns us to the beginning of the while block

https://github.com/nikic/PHP-Parser/blob/e4a54fa90a5cd8e8dd3fb4099942681731c5cdd3/lib/PhpParser/Lexer.php#L280

which prevents this bit of code of being executed, and thus we end with a `endLine` not being updated,

**Comment by j-d** [comment]
I think this issue is still happening on 4.0.3

**Comment by nikic** [comment]
This is semi-intentional, in that nop nodes are empty and as such have a token end offset that comes before the token start offset (in terms of closed intervals). What is subject to interpretation here is whether the end is fixed to the start minus one or can go back further (as is currently the case when whitespace and comments are involved).

Is the current behavior causing an issue in some context?

**Comment by nikic** [comment]
After https://github.com/nikic/PHP-Parser/commit/60d025a914aff02d9d7403bbe858e2553fa61f24 the start and end line of empty nops will be the same.
