### ISSUE TITLE
Changing comment content on $node doesn't save it

### ISSUE THREAD

**Issue by TomasVotruba** [nikic/PHP-Parser#486]
When I set the node on parent and return new node, the docs block changes: https://github.com/rectorphp/rector/pull/354/files#diff-e9a7d5b3acb3b838e3f4d562d0bdee95R113

Basically:

```php
$parentNode = $node->getAttribute('parent_node');
$doc = new Doc('new content');
$parentNode->setDocComment($doc);

return new Name('some name'); // any new node

// doc is changed
```

---

**But when I set it on the node passed to node traverser and return, it does not change:**
https://github.com/rectorphp/rector/pull/354/files#diff-e9a7d5b3acb3b838e3f4d562d0bdee95R143

Basically:

```php
$doc = new Doc('new content');
$node->setDocComment($doc);

return $node;

// doc is the same :(
```

See Travis: https://travis-ci.org/rectorphp/rector/jobs/352049418#L640

![image](https://user-images.githubusercontent.com/924196/37257303-10a92bee-2568-11e8-8987-34c8551c7933.png)

**Comment by nikic** [comment]
It looks like you're trying to change the doc comment on the variable node, rather than on the `Stmt\Expression` node. The fact that the variable also has the doc comment is a bug (https://github.com/nikic/PHP-Parser/issues/253) and the pretty printer will ignore it. Generally assigning a doc comment only makes sense for statements.

**Comment by TomasVotruba** [comment]
It works as you recommend it, thanks
