### ISSUE TITLE
Can't parse file due nesting level

### ISSUE THREAD

**Issue by webmake** [nikic/PHP-Parser#525]
I used library [maglnet/composer-require-checker](https://github.com/maglnet/ComposerRequireChecker) and analysed project which has [symfony/monolog-bundle](https://github.com/symfony/monolog-bundle), but fails when analizing with error
```
PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting!
```
Problematic file which [NodeTraverser](https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/NodeTraverser.php) can't handle is realy huge:
https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/Configuration.php

Maybe there can be added some nesting level check, that won't stop working at all?

**Comment by nikic** [comment]
You should either [increase your nesting level](https://github.com/nikic/PHP-Parser/blob/master/doc/2_Usage_of_basic_components.markdown#bootstrapping) or [disable XDebug entirely](https://github.com/nikic/PHP-Parser/blob/master/doc/component/Performance.markdown#xdebug). Disabling XDebug is strongly recommended, because it makes PHP much, much slower.

**Comment by webmake** [comment]
Worked perfectly, thanks
