### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by theofidry** [nikic/PHP-Parser#542]
I recently got an error when upgrading from PHP-Parser 4.0.4 to 4.1.0 with [this file](https://github.com/sebastianbergmann/diff/blob/e09160918c66281713f1c324c1f4c4c3037ba1e8/tests/ParserTest.php):

```bash
$ bin/php-parse vendor/sebastian/diff/tests/ParserTest.php
====> File /path/to/vendor/sebastian/diff/tests/ParserTest.php:
Invalid body indentation level (expecting an indentation level of at least 1) on line 78
```

I can't check in details before a while, but it seems related to the heredoc support changes

**Comment by nikic** [comment]
This is expected, as the code is no longer valid PHP code since PHP 7.3. Looks like it was fixed in https://github.com/sebastianbergmann/diff/commit/227f803c33aad0c004f77ca61815ee8e76d94788.

You can restore the previous behavior by using the `PhpParser\Lexer` class instead of `PhpParser\Lexer\Emulative`, but that will only work as long as you're running on PHP < 7.3. If you are running on 7.3 token_get_all() will interpret the code according to the new semantics.

**Comment by theofidry** [comment]
urg I see, ok I'll have to patch a couple of things on my side then. Thanks for the quick answer!
