### ISSUE TITLE
Cannot set default value when using shorthand Array syntax

### ISSUE THREAD

**Issue by level39** [nikic/PHP-Parser#557]
When assigning an array as default value, the exception:

`Call to a member function getComments() on int` is thrown.

This happens when using the shorthand syntax:

`$factory->property('commands')->setDefault(new Array_([1, 2, 3], ['kind' => Array_::KIND_SHORT]))`

But if the array is empty, the `Standard Printer` prints it just fine:

`$factory->property('commands')->setDefault(new Array_([], ['kind' => Array_::KIND_SHORT]))`

The exception is thrown when checking if the node has comments:

[https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/PrettyPrinter/Standard.php#L955](https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/PrettyPrinter/Standard.php#L955)

I'm working on a project that's going to generate a lot of code so a workaround or a fix would be much appreciated.

Thanks

**Comment by nikic** [comment]
The issue here is that `new Array_([1, 2, 3])` is not a valid node, it should be something like `new Array_([new ArrayElem(new LNumber(1)), ...])`, which is of course not very convenient to create. The builder automatically convert literals to the corresponding node trees, but you have to pass the actual literal, i.e. `->setDefault([1, 2, 3])` rather than `->setDefault(new Array_([1, 2, 3]))`.

This doesn't allow you to specify the array kind, but (unless you need a mix of short and long syntax) you can also handle this by constructing the pretty printer with the `['shortArraySyntax' => true]` option. That should be easier than specifying the desired syntax everywhere.

**Comment by level39** [comment]
@nikic 
Perfect. Thank you so much for your quick response.
