### ISSUE TITLE
Could I perserve the formatting when I appending some code to the last.

### ISSUE THREAD

**Issue by eeliu** [nikic/PHP-Parser#594]
## Example

> Origin

``` php
namespace app;


class Foo
{

}
```

> Wrapped 

``` php
namespace app;


class Foo
{

}
require 'header.php';
```

Below is my code

``` php

 public function handleLeaveNamespace(&$nodes){
            $expression= new Node\Stmt\Expression(
                new Node\Expr\Include_(
                    new Node\Scalar\String_($fullPath),Node\Expr\Include_::TYPE_REQUIRE
                )
            );
            $nodes->stmts[]  = $expression;  // while this can't make it, some blank lines are missing
            return $nodes;
    }
```
Could you help me !

**Comment by eeliu** [comment]
I made a mistaken on traverser. 
Hope not  bother everyone !

**Comment by TomasVotruba** [comment]
> I made a mistaken on traverser.

What was the mistake you made? So people having the same problem in the future could read the solution

**Comment by eeliu** [comment]
I add an empty array into addStmts when build ast.

**Comment by TomasVotruba** [comment]
I see, thanks for sharing.

I think you will experience more space issues in the future. AST is not designed to work with spacing, compared to coding standards that have this job as #1.

That's why I recommend to use any coding standard tool that will clean up after big AST changes :)

You can read more here:
https://github.com/rectorphp/rector/blob/master/README.md#how-to-apply-coding-standards

I wore about these tools here and when to use them here: https://www.tomasvotruba.cz/blog/2018/10/22/brief-history-of-tools-watching-and-changing-your-php-code/

**Comment by eeliu** [comment]
@TomasVotruba 
Thanks for you supporting, I will share these to other members and thanks again.
