### ISSUE TITLE
[PHP 8] attributes 2 support

### ISSUE THREAD

**Issue by TomasVotruba** [nikic/PHP-Parser#659]
This might be fun :). I would like to give it try, if you haven't made it yet.

How could we handle it? 
What apart grammar needs to be done?
We could use similar approach as for docblocks.

Also, how should we name it? There are already, attributes at each node.

Grammar: https://github.com/beberlei/php-src/blob/ea9277b9a416a1bd13217ead0a4c58bad1eaaf85/Zend/zend_language_parser.y

**Comment by nikic** [comment]
This should be fairly easy to add, shouldn't be much more than grammar adjustments, adding an `attributes` subnode where appropriate and making sure that NameResolver handles it.

> Also, how should we name it? There are already, attributes at each node.

Good question. I'm not sure about this part... Maybe we could call it `attrs` instead of `attributes` to avoid the conflict. Or rename existing `attributes` to something like `nodeAttributes`.

**Comment by TomasVotruba** [comment]
> Or rename existing attributes to something like nodeAttributes.
 
I think that's more clear :+1: 

I'll look into it this week.

**Comment by TomasVotruba** [comment]
Follow up PHP RFC:

- https://wiki.php.net/rfc/shorter_attribute_syntax
- https://wiki.php.net/rfc/attribute_amendments

**Comment by nikic** [comment]
Doing the lexer emulation for the new `#[]` syntax is extremely hard :(

**Comment by TomasVotruba** [comment]
:partying_face: :tada:
