### ISSUE TITLE
ComposerRequireChecker: Syntax error, unexpected T_NS_SEPARATOR on line 122

### ISSUE THREAD

**Issue by kochen** [nikic/PHP-Parser#700]
Hi,
in a project that uses [api-platform/core](https://github.com/api-platform/core), we use [maglnet/ComposerRequireChecker](https://github.com/maglnet/ComposerRequireChecker) to check our dependencies.
Due to a recent update of [vimeo/psalm](https://github.com/vimeo/psalm/compare/3.13.1...3.14.0#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R30), `PHP-Parser` got updated to `4.8` which resulted in the error below when running the `ComposerRequireChecker`:
```
Syntax error, unexpected T_NS_SEPARATOR on line 122
```

I managed to narrow it down to these specific packages and versions:
* `api-platform/core:2.5.6`
* `maglnet/composer-require-checker:2.1.0`
* `nikic/php-parser:4.7.0`

Downgrading to `nikic/php-parse:4.6.0` "solves" the problem.
Upgrading to either `4.8` or `4.9` does NOT solve the issue.

I've create a dedicated repo with the above mentioned packages/version, that can be used to reproduce the problem: https://github.com/kochen/nikic-php-parser-4.7.0

**Comment by kochen** [comment]
Issue seems to be "gone" with the release of [api-platform/core:2.5.7](https://github.com/api-platform/core/releases/tag/v2.5.7)

**Comment by nikic** [comment]
`api-platform/core` was one of the few packages incompatible with https://wiki.php.net/rfc/namespaced_names_as_token:

```
api-platform/core/src/Metadata/Extractor/AbstractExtractor.php:121
    \ RuntimeException
```

When PHP-Parser switched to the new interpretation of namespaced names, I expect it choked on that code. Presumably this has been fixed in the newest version of api-platform/core.

I don't plan to support the old interpretation in this package, so I'm closing this issue.
