### ISSUE TITLE
array_splice calls slow

### ISSUE THREAD

**Issue by kkmuffme** [nikic/PHP-Parser#838]
Did some profiling and for some reason array_splice is extremely slow.
Had it called ~7000 times with a total duration of 8.5s in PhpParser/Lexer.php `function postprocessTokens`

Is there any possibility of improving this code?

**Comment by TomasVotruba** [comment]
Hi, what is the reproducible code snippet?
Which of the `array_splice()` in the `function postprocessTokens` are responsible? 
How can we improve the performance with same result?

**Comment by kkmuffme** [comment]
I don't have one. Just run it on a sufficiently large file.

All 3 it seems.

I don't know. That was my question too.

**Comment by TomasVotruba** [comment]
We'll need a reproducer repository.

**Comment by nikic** [comment]
It should be possible to optimize this by creating a new tokens array instead of modifying it in place.

Though you can also fix this by running on a modern PHP version. I believe this only affects emulation code that is necessary on PHP 7, but not PHP 8.

**Comment by kkmuffme** [comment]
Yeah I'm on PHP 7.4.
Will try on PHP8 in the next weeks, to see if that solves the issue

**Comment by dryabov** [comment]
> It should be possible to optimize this by creating a new tokens array instead of modifying it in place.

Ideally (if someone does like to support 7.x), to populate a list of changes (with elements `[offset, length, [replacement]]` similar to `array_splice` arguments), and at the end of postprocessing check this list:
- if it is empty, then just return,
- (optionally) if its length is 1, then call `array_splice` and return,
- otherwise, create new tokens array, populate it using `array_slice`/`array_merge`/`array_push` (alternative way would be to append new tokens to `$this->token`, remove combining sequences, prepare a properly sorted keys mapping, and use `array_combine` to rearrange elements, but I'm not sure it will be much faster), and finally update `$this->token` by the new array.

**Comment by kkmuffme** [comment]
The issue was due to a badly coded plugin, which did not correctly cache data.

Could not reproduce anymore with PHP 7.4 either.
