### ISSUE TITLE
Best way to determine if any changes were made to AST?

### ISSUE THREAD

**Issue by rulatir** [nikic/PHP-Parser#900]
Since format-preserving prettyprinting has been experimental for years and will most likely never be capable of rendering unmodified AST to unmodified PHP in every case, I need an alternative strategy for detecting a no-changes-made condition betwen the before AST and the after AST. This is necessary to avoid generating whitespace/formatting-only file changes during large refactorings.

I would like to avoid having to manually track when I make a change (e.g. by setting a flag in the visitor), because that is an immense burden to always remember when writing lots and lots and lots and lots of visitor code.

**Comment by nikic** [comment]
> Since format-preserving prettyprinting has been experimental for years and will most likely never be capable of rendering unmodified AST to unmodified PHP in every case

Any particular case you ran into? I'd have expected the "completely unmodified" case to work reliably.

> I need an alternative strategy for detecting a no-changes-made condition betwen the before AST and the after AST. This is necessary to avoid generating whitespace/formatting-only file changes during large refactorings.

I think doing the same thing as the formatting-preserving pretty printer should work, i.e. use the CloningVisitor and then compare against origNode (recursively).

**Comment by nikic** [comment]
I did identify two cases where formatting was not preserved for completely unmodified AST, fixed in https://github.com/nikic/PHP-Parser/commit/a3bc900a41b337266c0af359e38638968e10b9f1 and https://github.com/nikic/PHP-Parser/commit/bb4263ea1a36455b7942debf53edc8329ad01e31. If there are others, I'd love to know about them.

As to the original question, the approach I actually use to check whether two ASTs are the same for testing purposes is this:
```php
$nodeDumper = new PhpParser\NodeDumper;
$same = $nodeDumper->dump($stmts) == $nodeDumper->dump($stmts2);
```
That's probably the simplest way to do it.
