### ISSUE TITLE
Parser instance is not automatically garbage collected due to self references

### ISSUE THREAD

**Issue by vudaltsov** [nikic/PHP-Parser#980]
```php

use PhpParser\Lexer;
use PhpParser\Parser\Php7;

gc_disable();

function createParser(): void
{
    new Php7(new Lexer());
}

for ($i = 0; $i < 4; ++$i) {
    createParser();
    echo memory_get_usage().PHP_EOL;
}
```

outputs

```
7992640
8279744
8558624
8853888
```

This is due to non-static closures in Parser:
https://github.com/nikic/PHP-Parser/blob/ce019e9ad711e31ee87c2c4c72e538b5240970c3/lib/PhpParser/Parser/Php7.php#L1138-L1143

If I manually clean up the `$reduceCallbacks` property, memory will stay constant:

```php
use PhpParser\Lexer;
use PhpParser\Parser\Php7;

gc_disable();

function createParser(): void
{
    $parser = new Php7(new Lexer());
    (function () {
        $this->reduceCallbacks = [];
    })->call($parser, $parser::class);
}

for ($i = 0; $i < 4; ++$i) {
    createParser();
    echo memory_get_usage().PHP_EOL;
}
```
```
7712640
7712672
7712672
7712672
```

**Comment by nikic** [comment]
I didn't measure a performance overhead from passing $this as a parameter, so I went ahead and did that. This avoids the cycle.

Note though that the intended use of the parser is to create an instance once and then reuse it many times, rather than creating new instances for each parse. Doing that is inefficient for other reasons as well (e.g. because we're going to recompute the token mapping every time the parser is constructed.)

**Comment by nikic** [comment]
That's a good point. I'm probably doing the same in tests...

**Comment by vudaltsov** [comment]
Are you going to apply the fix to v4?
